---
language: python
os:
  - linux
dist: focal

python:
  - "3.8"
  - "3.9-dev"
  - "nightly"

notifications:
  irc:
    if: fork = false
    channels:
      - "chat.freenode.net#ponymail"
  email:
    if: fork = false
    recipients:
      - dev@ponymail.apache.org

before_script:
  - pip install mypy

script:
  - mypy --ignore-missing-imports tools/archiver.py

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      before_script: git clone https://github.com/apache/incubator-ponymail-unit-tests.git tests
      script: cd tests && python3 runall.py --rootdir ../
