---
language: python
os:
  - linux
dist: focal

python:
  - "3.8"
  - "3.9-dev"
  - "nightly"

notifications:
  irc:
    if: fork = false
    channels:
      - "irc.libera.chat#ponymail"
  email:
    if: fork = false
    recipients:
      - dev@ponymail.apache.org

before_script:
  - pip install mypy

script:
  - mypy --ignore-missing-imports tools/archiver.py
  - mypy --ignore-missing-imports tools/import-mbox.py
  - mypy --ignore-missing-imports server/main.py
  - mypy --ignore-missing-imports server/plugins/*.py
  - mypy --ignore-missing-imports server/endpoints/*.py

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      before_script:
        - git clone https://github.com/apache/incubator-ponymail-unit-tests.git tests
        - pip install html2text
        - sed -e 's/# cropout:/cropout:/' tools/ponymail.yaml.example >tools/ponymail.yaml
      script: cd tests && python3 runall.py --rootdir ../
