#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  pmfoal:
    image: pmfoal
    build: .
# Port 1080 must agree with the oauth_portal user and admin entries in config.js
# Expose port 9200 to give access to ElasticSearch from the host
    ports:
      - "1080:80"
      - "9200:9200"
    volumes:
      - .:/var/www/ponymail
      - ./elastic/lib:/var/lib/elasticsearch
      - ./elastic/log:/var/log/elasticsearch
