services:
  pmfoal:
    image: pmfoal
    build: .
# Port 1080 must agree with the oauth_portal user and admin entries in config.js
# Expose port 9200 to give access to ElasticSearch from the host
    ports:
      - "1080:80"
      - "9200:9200"
# MAIL_DATA can be used to map external mailboxes into the container
    volumes:
      - .:/var/www/ponymail
      - ./elastic/lib:/var/lib/elasticsearch
      - ./elastic/log:/var/log/elasticsearch
      - ${MAIL_DATA:-.}:/var/maildata
