name: Integration Tests

# TODO: add some useful tests

on:
  # Don't currently want this to run every time

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    services:

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
        # <port on host>:<port on container>
        - 9200:9200
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt
    - name: Basic test
      run: |
        curl -sq "http://localhost:9200/_cluster/health?level=indices&pretty"
    - name: Database setup
      run: |
        cd tools
        ./setup.py --defaults --devel
    - name: Show Database
      run: |
        curl -sq "http://localhost:9200/_cat/indices?v"
        curl -sq "http://localhost:9200/_settings?pretty"
        curl -sq "http://localhost:9200/ponymail-mbox/_mapping?pretty"
        curl -sq "http://localhost:9200/ponymail-source/_mapping?pretty"

  background:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
    - name: Server
      run: |
        cd server
        python main.py --apilog INFO --logger INFO

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt
    - name: preferences1
      run: |
        curl -sq http://localhost:8080/api/preferences.lua
    - name: load Database
      run: |
        tools/import-mbox.py --source tests/resources/rfc2822-A5.eml --lid a.b.c
    - name: Show Database
      run: |
        curl -sq "http://localhost:9200/_cat/indices?v"
    - name: preferences2
      run: |
        curl -sq http://localhost:8080/api/preferences.lua
# TODO: ideally at the end of this job, stop the background job
