name: Foal Type Tests

on: 
  push:
    paths-ignore:
      - '**/integration-tests.yml'
      - 'test/itest*'
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        # 3.8 EOL 2024-10 approx
        python-version: [3.8, "3.10", 3.12]
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt
        pip install -r server/requirements.txt
        pip install mypy
        pip list
    - name: Type testing with mypy
      run: |
          mypy --cache-dir /tmp/ --install-types
          mypy --cache-dir /tmp/ --ignore-missing-imports tools/*.py
          mypy --cache-dir /tmp/ --ignore-missing-imports server/*.py
          mypy --cache-dir /tmp/ --ignore-missing-imports server/plugins/*.py
          mypy --cache-dir /tmp/ --ignore-missing-imports server/endpoints/*.py
