name: Foal Type Tests

on: 
  push:
    paths:
      - '**/type-tests.yml'
      - '**/*.py'
      - '**/requirements.txt'
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        # 3.8 EOL 2024-10 approx
        python-version: [3.8, 3.12, "3.10"]
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt
        pip install -r server/requirements.txt
        # mypy crashes: resolver.py:19: error: INTERNAL ERROR -- Please try using mypy master on GitHub
        git clone https://github.com/python/mypy.git /tmp/mypy
        python3 -m pip install --upgrade /tmp/mypy
        pip list
    - name: Type testing with mypy
      run: |
          mypy --cache-dir /tmp/ --install-types
          mypy --cache-dir /tmp/ --ignore-missing-imports tools/*.py
          mypy --cache-dir /tmp/ --ignore-missing-imports server/*.py
          mypy --cache-dir /tmp/ --ignore-missing-imports server/plugins/*.py
          mypy --cache-dir /tmp/ --ignore-missing-imports server/endpoints/*.py
