name: Unit Tests

on:
  push:
    paths-ignore:
      - '**/integration-tests.yml'
      - '**/type-tests.yml'
      - '**/linting.yml'
      - 'test/itest*'
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false # test all Python versions
      matrix:
        # Add 3.11 to see if it shows failures like 3.12
        python-version: ["3.10", 3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # need all versions to be able to access server tree commit logs
        persist-credentials: false
    - uses: actions/checkout@master   
      with:
        persist-credentials: false
        repository: apache/incubator-ponymail-unit-tests
        path: pmtests
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt
        pip install -r test/requirements.txt
        # Later versions of html2text cause html-based tests to fail, because of a changed conversion
        # This only affects the appearance of the message body, so does not matter for compatibility
        pip install html2text==2020.1.16 # optional dependency, but needed for tests
        pip list
    - name: Check versions
      run: |
        webui/js/source/build.sh
        server/update_version.sh
    - name: Test with pytest
      run: |
        cp tools/archiver.yaml.example tools/archiver.yaml
        python -m pytest test/test_*.py
    - name: Test with Ponymail Unit tests
      run: |
        sed -e '/incubator/s/# cropout:/cropout:/' tools/archiver.yaml.example >tools/archiver.yaml
        cd pmtests
        python runall.py --root ..
